name: shmr_finance
description: "SHMR finance tracker homework"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  flutter_svg: ^2.1.0
  flutter_bloc: ^9.1.1
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  category_chart:
    path: category_chart

  balance_chart:
    path: balance_chart

dev_dependencies:
  flutter_test:
    sdk: flutter
  provider: ^6.1.5
  freezed: ^3.0.6
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  fuzzy: ^0.5.1
  sensors_plus: ^4.0.2
  device_info_plus: ^10.1.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/

flutter_gen:
  localizations:
    arb-dir: lib/l10n
    template-arb-file: app_en.arb
    output-localization-file: app_localizations.dart
    output-class: AppLocalizations